# Generated by Django 3.0.3 on 2020-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResPartnerNroConector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'res_partner_nro_conector',
                'managed': False,
            },
        ),
    ]
